import * as bannerRepository from '../../repository/admin/bannerRepository.js';
import { S3Client, DeleteObjectCommand } from '@aws-sdk/client-s3';

// For retrieve 'all' banner documents
export const fetchAllBannersForAdmin = async () => {
    const banners = await bannerRepository.getAllBanners();                     // Retrieve 'all' banner documents and 'sort' as 'newly created' for 'displaying'(ie 'lean()')it.
    return { banners };
};

// For 'process' of create 'new' banner and return a 'resolved' or 'rejected' 'Promise'.
export const processNewBanners = async (bodyData, filesData) => {               // Here 'bodyData'(ie 'req.body')and 'fileData'(ie 'req.files')passes as 'arguments'.
    if (!filesData || filesData.length === 0) {
        throw new Error("At least one banner image file is required.");
    }
    if (filesData.length > 5) {
        throw new Error("You can only upload a maximum of 5 images at once.");
    } 
    const bannerPromises = filesData.map(item => {                              //  'filesData' is 'req.files' it contains 'multiple' image files and metadata created by 'multer' when data get from '<input type=file' from 'user' side and here we iterate the array for 'structuring' it fro save in data base.                      
        const bannerData = {
            title: bodyData.title.trim(),
            targetUrl: bodyData.targetUrl ? bodyData.targetUrl.trim() : '',
            placement: bodyData.placement,
            isActive: bodyData.isActive === 'on',
            imageUrl: item.location || item.path 
        };
        return bannerRepository.createBanner(bannerData);                         // For 'create'  a new 'banner' document in 'data base'
    });
    return await Promise.all(bannerPromises);                                     // Here 'map()' return an a 'new' array of 'Promise' object, because we ‘returning’ ‘.createBanner(bannerData)’(ie we use ‘create()’ in it and it done ‘both’ ‘save’ data into ‘data base’ and also ‘return’ this data’ as ‘js’ object)and so we can use 'Promise.all()'(ie it return 'only' 'resolved' or 'rejected' 'Promise') for handle all returning ‘items/image’ asynchronously, after ‘saving’ data in ‘database’. 
};



// Retrieve 'banner' based on 'id'.
export const fetchBannerById = async (id) => {
    const banner = await bannerRepository.findBannerById(id);                     // Retrieve 'only' 'one' banner based on 'id'
    if (!banner) {
        throw new Error("Banner not found");
    }
    return banner;
};



// Create 'aws s3' instance for delete the 'old' image from 'aws'
const s3 = new S3Client({
    region: process.env.AWS_REGION,
    credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY,
        secretAccessKey: process.env.AWS_SECRET_KEY
    }
});

// For update new data and 'delete' existing data like image etc from 'aws'
export const processEditBanner = async (id, bodyData, fileData) => {
    const existingBanner = await bannerRepository.findBannerById(id);               // Retrieve banner based on 'id'
    if (!existingBanner) {
        throw new Error("Banner not found.");
    }
    const updateData = {
        title: bodyData.title.trim(),                                               // Here 'bodydata' is the 'arguement' get from 'req.body'
        targetUrl: bodyData.targetUrl ? bodyData.targetUrl.trim() : '',
        placement: bodyData.placement,
        isActive: bodyData.isActive === 'on'
    };
    if (fileData && fileData.location) {                                            // 'location' is the final 'AWS S3' 'url', generated by the 'multer-s3' middleware after a successful upload through '<form>'.
        updateData.imageUrl = fileData.location;
        if (existingBanner.imageUrl && existingBanner.imageUrl.includes('amazonaws.com')) {  // It is the 'safty check' ie prevents from crash the application by check 'imageUrl' contains the string' 'amazonaws.com',because when we uploading time in all imageUrl we put ''amazonaws.com' automatically
            try {
                const urlObj = new URL(existingBanner.imageUrl);
                const fileKey = urlObj.pathname.substring(1);                      // Here 'urlObj' 'string' url contains all data includes 'pathname'(ie '/banners/sale.jpg')and we want to retrieve without '/' so 'substring()' the 'js' 'string' method remove 'first' character(ie it start from '1st' index or we can use 'slice(1)' get same result) in the 'string'.    
                await s3.send(new DeleteObjectCommand({                            // Here we 'import' 'new DeleteObjectCommand()' from the '@aws-sdk/client-s3' library and configure it with 'bucket name' and the 'file key' for 'delete'(ie we 'delete' existing 'banner' image 'url' from 'aws' server and add new one)it and 's3.send()' is built-in method used for send it to 'aws' server through 'node.js'
                    Bucket: process.env.AWS_BUCKET_NAME,
                    Key: fileKey
                }));
            } catch (s3Error) {
                console.error("AWS S3 Old Image Deletion Failed:", s3Error);
            }
        }
    }
    return await bannerRepository.updateBannerById(id, updateData);                // Find the 'banner' document based on 'id' and 'update' based on 'updateData' and return this 'updated' document(ie 'new: true')
};

// For 'delete' old banner from 'awss3' 
export const removeBanner = async (id) => {
    const banner = await bannerRepository.findBannerById(id);                     // Retrieve banner based on 'id'
    if (!banner) {
        throw new Error("Banner not found");
    }
    if (banner.imageUrl && banner.imageUrl.includes('amazonaws.com')) {
        try {
            const urlObj = new URL(banner.imageUrl);
            const fileKey = urlObj.pathname.substring(1); 
            const deleteParams = {
                Bucket: process.env.AWS_BUCKET_NAME,
                Key: fileKey
            };
            await s3.send(new DeleteObjectCommand(deleteParams));
        } catch (s3Error) {
            console.error("AWS S3 Deletion Failed:", s3Error);
        }
    }
    return await bannerRepository.deleteBannerById(id);
};